name: Deploy using AWS SSM Send-Command 

on:
 push:
  branches: [main]

jobs:
 start:
  runs-on: ubuntu-latest 

  steps:
  - uses: actions/checkout@v4

  - name: AWS SSM Send Command
    uses: peterkimzz/aws-ssm-send-command@master
    with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
     aws-region: us-east-1
     instance-ids: ${{ secrets.INSTANCE_ID  }}
     comment: Deploy the master branch
     working-directory: /home/ubuntu/portfolio
     command: /bin/bash ./deploy.sh
