name: Deploy Django to EC2

on:
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout repository
    uses: actions/checkout@v2
  - name: Run Deployment
    run: |
      ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@ec2-54-92-164-66.compute-1.amazonaws.com 'bash -s' < /home/ubuntu/portfolio/deploy.sh
    env:
      ACTIONS_RUNNER_DEBUG: false
