name: Deploy using AWS SSM Send-Command 

on:
 push:
  branches: [main]

jobs:
 start:
  runs-on: ubuntu-latest 

  steps:
  - uses: actions/checkout@v4

  - name: AWS SSM Send Command
    uses: nohmad/aws-ssm-send-command-action@master
    with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
     aws-region: us-east-1
     targets: |
      [{"Key":"InstanceIds","Values":[secrets.INSTANCE_ID]}]
     document-name: AWS-RunShellScript
     parameters: |
      {"commands": ["cd /home/ubuntu/portfolio", "/bin/bash ./deploy.sh"]}
