name: Deploy using AWS SSM Send-Command 

on:
 push:
  branches: [main]

jobs:
 start:
  runs-on: ubuntu-latest 

  steps:
  - uses: actions/checkout@v4

  - name: AWS SSM Send Command
    uses: peterkimzz/aws-ssm-send-command@1.0.4
    with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
     aws-region: us-east-1
     targets: |
      [{"Key":"InstanceIds","Values":["i-042035378b2f17a70"]}]
     document-name: AWS-RunShellScript
     parameters: |
      {"commands":["/bin/bash ./deploy.sh"], "workingDirectory":["/home/ubuntu/portfolio"]}
